version: '3.8'

services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ${HOME}/secrets/sis:/app/config/secrets
    container_name: sis
    
    user: 1001320000:10000
    group_add:
      - '0'
